config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # Devise
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }
  #             path_names: { sign_in: '', sign_up: 'inscription', sign_out: 'deconnecter'}
  #             path: '',

  # if Rails.env == "development"
  #   devise_for :users, controllers: { registrations: 'registrations' }
  # elsif Rails.env == "production"
  #   devise_for :users, controllers: { registrations: 'users/registrations' }
  # end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # devise_scope :user do
  #   delete 'users/:id/delete-account', to: 'registrations#admin_destroy', as: :admin_destroy
  # end

  # Pages
  # get '/a-propos', to: 'pages#about_us', as: :about_us
  # get '/mentions-legales', to: 'pages#legal_notice', as: :legal_notice
  get '/accueil', to: 'pages#home', as: :home
  # root to: 'pages#home'
  get '/conditions-generales-de-vente', to: 'pages#cgv', as: :cgv
  get '/mes-profils-compatibles', to: 'pages#profil_match', as: :profil_match
  get '/admin-dashboard', to: 'pages#admin_dashboard', as: :admin_dashboard
  get '/admin-dashboard/profils', to: 'pages#admin_dashboard_profils', as: :admin_dashboard_profils
  get '/admin-dashboard/orders', to: 'pages#admin_dashboard_orders', as: :admin_dashboard_orders
  get '/admin-dashboard/messages', to: 'pages#admin_dashboard_messages', as: :admin_dashboard_messages
  get '/admin-dashboard/pages', to: 'pages#admin_dashboard_pages', as: :admin_dashboard_pages
  get '/profil/:slug', to: 'pages#profil', as: :profil
  get '/mes-favoris', to: 'pages#my_favorites', as: :my_favorites
  get '/profils-recherches', to: 'pages#search_profils', as: :search_profils
  get '/stories/:slug', to: 'pages#my_stories', as: :my_stories
  get '/stories', to: 'pages#all_stories', as: :all_stories
  delete 'users/:id/delete_photo_attachment', to: 'pages#delete_photo_attachment', as: :delete_photo_attachment_user
  get '/check-credit-activated', to: 'pages#check_credit_activated', as: :check_credit_activated
  # get '/mini-jeux', to: 'pages#applications', as: :applications
  patch '/user-banned/:id', to: 'pages#user_banned', as: :user_banned
  get '/profils-a-cote-de-ma-position-actuelle', to: 'pages#next_to_current_position', as: :next_to_current_position
  get '/update_position', to: 'pages#update_user_position',  as: :update_position

  # pages model
  get '/pages/:id/edit', to: 'pages#edit', as: :edit_page
  patch '/pages/:id', to: 'pages#update', as: :page
  put '/pages/:id', to: 'pages#update'

  # contact
  post '/contacts', to: 'messages#create', as: :messages
  get '/contact', to: 'messages#new', as: :new_message

  # favorites
  post '/favoris', to: 'favorites#create'
  delete '/favoris/:id', to: 'favorites#destroy', as: :favorite

  # publications
  get '/mur-des-publications', to: 'publications#filtered_index', as: :publications
  post '/mur-des-publications', to: 'publications#create'
  get '/publications/:id/edit', to: 'publications#edit', as: :edit_publication
  patch '/publications/:id', to: 'publications#update', as: :publication
  put '/publications/:id', to: 'publications#update'
  delete '/publications/:id', to: 'publications#destroy'

  # contact requests
  get '/mes-demandes-de-contact', to: 'contact_requests#filtered_index', as: :contact_requests
  post '/mes-demandes-de-contact', to: 'contact_requests#create'
  delete '/mes-demandes-de-contact/:id', to: 'contact_requests#destroy', as: :contact_request # destroy useless
  patch '/demande-de-contact-acceptee/:id', to: 'contact_requests#mark_as_accepted', as: :mark_as_accepted
  patch '/demande-de-contact-cachee/:id', to: 'contact_requests#hide_contact_request', as: :hide_contact_request

  # notifications
  get '/notifications', to: 'notifications#filtered_index', as: :notifications
  patch '/mode-invisible', to: 'notifications#ninja_mode', as: :ninja_mode
  patch '/notification-cachee/:id', to: 'notifications#hide_notification', as: :hide_notification

  # blockages
  get '/mes-comptes-bloques', to: 'blockages#filtered_index', as: :blockages
  post '/mes-comptes-bloques', to: 'blockages#create'
  delete '/mes-comptes-bloques/:id', to: 'blockages#destroy', as: :blockage

  # orders
  get '/mes-commandes', to: 'orders#filtered_index', as: :orders
  post '/mes-commandes', to: 'orders#create'
  delete '/mes-commandes/:id', to: 'orders#destroy', as: :order
  get '/ma-commande-en-cours', to: 'orders#current_order', as: :current_order
  get '/tarifs', to: 'orders#choose_prices', as: :choose_prices
  get '/mes-commandes/:id/payer', to: 'orders#pay_order', as: :pay_order
  get '/panier', to: 'orders#basket', as: :basket
  patch '/annuler-abonnement', to: 'orders#unsubcribed', as: :unsubcribed

  # payment page
  get '/mes-commandes/panier/:order_id/paiement', to: 'payments#new', as: :new_order_payment

  # chatrooms
  get '/chatrooms', to: 'chatrooms#index', as: :chatrooms
  get '/chatrooms/:id', to: 'chatrooms#show', as: :chatroom
  patch '/chatrooms/:id/depense-credit', to: 'chatrooms#use_credit', as: :use_credit

  # posts
  post '/chatrooms/:chatroom_id/posts', to: 'posts#create', as: :chatroom_posts

  # payment_intents
  get '/commandes/:order_id/paiements', to: 'payment_intents#filtered_index', as: :payment_intents
  patch '/commandes/:order_id/paiements/:id', to: 'payment_intents#refund', as: :refund
  patch '/paiements/:id/mise-a-jour-statut', to: 'payment_intents#check_refund_status', as: :check_refund_status

  # games
  # get '/jeux', to: 'games#index', as: :games
  # get '/jeux/:id', to: 'games#show', as: :game

  # error pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Stirpe webhook
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Sidekiq Web UI, only for admins.
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: "sender_id"
  belongs_to :receiver, class_name: 'User', foreign_key: "receiver_id"
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  after_action :mark_as_read, only: [:filtered_index]

  def filtered_index
    authorize ContactRequest.new
    blockages = find_blockages

    @contact_requests_sent = policy_scope(ContactRequest).includes(:sender, receiver: :avatar_attachment).where(sender: current_user, visible_sender: true).order(id: :desc).reject { |contact_request| blockages.include?(contact_request.receiver) || contact_request.receiver.banned? }.paginate(page: params[:page], per_page: 50)
    @contact_requests_received = policy_scope(ContactRequest).includes(sender: :avatar_attachment).where(receiver: current_user, visible_receiver: true).order(id: :desc).reject { |contact_request| blockages.include?(contact_request.sender) || contact_request.sender.banned? }.paginate(page: params[:page], per_page: 50)
    @nbr_new_contact_requests = policy_scope(ContactRequest).includes(:receiver).where(receiver: current_user, readed: false).size
  end

  def create
    receiver_id = contact_request_params["receiver_id"].to_i
    @receiver = User.find(receiver_id)

    @contact_request = ContactRequest.new
    @contact_request.sender = current_user
    @contact_request.receiver = @receiver
    authorize @contact_request

    if @contact_request.save
      CreateNotificationJob.perform_later(current_user, @receiver, helpers.notifications_contact_request)
      if @contact_request.receiver.notification_contact_request_received?
        NotificationMailer.with(receiver: @contact_request.receiver, sender: @contact_request.sender).contact_request_received.deliver_later
      end

      respond_to do |format|
        format.js
        format.html { redirect_back fallback_location: profil_path(@contact_request.receiver.slug), notice: "Votre demande de contact a bien été envoyé à #{@receiver.pseudo}." }
      end
    else
      redirect_back fallback_location: profil_path(@contact_request.receiver.slug), alert: "Erreur de saisie."
    end
  end

  def destroy
    @contact_request = authorize policy_scope(ContactRequest).find(params[:id])

    if @contact_request.accepted?
      redirect_back fallback_location: profil_path(@contact_request.receiver.slug), alert: 'Vous ne pouvez pas supprimer une demande de contact qui a été acceptée.'
    else
      @contact_request.destroy

      respond_to do |format|
        format.js
        format.html { redirect_back fallback_location: profil_path(@contact_request.receiver.slug), notice: 'Votre demande de contact a bien été supprimée.' }
      end
    end
  end

  def mark_as_accepted
    @contact_request = authorize policy_scope(ContactRequest).find(params[:id])

    if @contact_request.update(accepted: true)
      CreateNotificationJob.perform_later(@contact_request.receiver, @contact_request.sender, helpers.notifications_contact_request_accepted)
      if @contact_request.sender.notification_contact_request_accepted?
        NotificationMailer.with(receiver: @contact_request.receiver, sender: @contact_request.sender).contact_request_accepted.deliver_later
      end

      CreateChatroomJob.perform_later(@contact_request.sender, @contact_request.receiver)

      respond_to do |format|
        format.js
        format.html { redirect_back fallback_location: contact_requests_path, notice: "Vous venez d'accepter la demande de contact de #{@contact_request.sender.pseudo}." }
      end
    else
      redirect_back fallback_location: contact_requests_path, alert: "Une erreur est survenue."
    end
  end

  def hide_contact_request
    @contact_request = authorize policy_scope(ContactRequest).find(params[:id])

    if @contact_request.sender == current_user
      HideElementSenderJob.perform_later(@contact_request)
    elsif @contact_request.receiver == current_user
      HideElementReceiverJob.perform_later(@contact_request)
    end

    respond_to do |format|
      format.js
      format.html { redirect_back fallback_location: contact_requests_path, notice: 'La demande de contact a bien été cachée.' }
    end
  end

  private

  def contact_request_params
    params.require(:contact_request).permit(:receiver_id)
  end

  def mark_as_read
    contact_requests_received_not_readed = policy_scope(ContactRequest).where(receiver: current_user, readed: false)

    contact_requests_received_not_readed.each do |contact_request|
      MarkAsReadJob.perform_later(contact_request)
      CreateNotificationJob.perform_later(contact_request.receiver, contact_request.sender, helpers.notifications_contact_request_readed)
      if contact_request.sender.notification_contact_request_readed?
        NotificationMailer.with(receiver: contact_request.receiver, sender: contact_request.sender).contact_request_readed.deliver_later
      end
    end
  end
end

app/views/contact_requests/create.js.erb
contactRequestButton = document.getElementById('cr-button');
sendMessage = document.getElementById('cr-sent-message');

// hidden the deleted contact request
contactRequestButton.classList.add('hidden');
sendMessage.classList.remove('hidden');

app/views/contact_requests/destroy.js.erb
contactRequest = document.getElementById('cr-<%= @contact_request.id %>');

// hidden the deleted contact request
contactRequest.classList.add('hidden');

app/views/contact_requests/filtered_index.html.erb
<div class="bg-gradient">
  <div class="container bg-white py-5">

    <!-- title -->
    <h1 class="text-center mb-5">Mes demandes de contact</h1>

    <div class="row text-center">

      <!-- sent -->
      <div class="col-12 col-md-6 order-1">
        <h2 class="my-4">Envoyées</h2>
        <% if @contact_requests_sent.empty? %>
          <p><em>aucune</em></p>
        <% else %>
          <% @contact_requests_sent.each do |contact_request| %>

            <div class="notification" id="cr-<%= contact_request.id %>">
              <% if contact_request.receiver.avatar.attached? %>
                <% if contact_request.receiver.avatar.content_type == mp4_content_type %>
                  <%= cl_video_tag contact_request.receiver.avatar.key, transformation: [ crop: "fill" ], class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
                <% else %>
                  <%= cl_image_tag contact_request.receiver.avatar.key, crop: :fill, class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
                <% end %>
              <% else %>
                <%= image_tag 'avatar-profil.png', class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
              <% end %>
              <div class="notification-content text-left">
                <p>
                  <small class="text-dark"><%= contact_request.created_at.to_date.strftime("%d/%m/%Y") %>, <%= link_to contact_request.receiver.pseudo, profil_path(contact_request.receiver.slug), class: "text-decoration-none font-weight-bold" %></small>
                </p>
                <p>
                  <% if contact_request.accepted? %>
                    <%= notifications_contact_request_accepted %>
                  <% elsif contact_request.readed? %>
                    <%= notifications_contact_request_readed %>
                  <% else %>
                    <%= notifications_contact_request_sent %>
                  <% end %>
                </p>
              </div>
              <div class="notification-actions">
                <% if contact_request.accepted? %>
                  <i class="far fa-check-square" title="la demande a été acceptée"></i>
                <% end %>
                <% if policy(contact_request).hide_contact_request? %>
                  <p>
                    <%= link_to hide_contact_request_path(contact_request.id), remote: true, method: :patch, aria: { label: 'cacher cette demande de contact' } do %>
                      <i class="fas fa-eye-slash text-orange" title="Cacher cette demande de contact"></i>
                    <% end %>
                  </p>
                <% end %>
              </div>
            </div>

          <% end %>
          <%= will_paginate @contact_requests_sent, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
        <% end %>
      </div>

      <!-- received -->
      <div class="col-12 col-md-6 order-2 mt-5 mt-md-0">
        <h2 class="my-4">Reçues <span class="<%= @nbr_new_contact_requests.positive? ? 'counter' : '' %>"><%= @nbr_new_contact_requests.positive? ? @nbr_new_contact_requests : '' %></span></h2>
        <% if @contact_requests_received.empty? %>
          <p><em>aucune</em></p>
        <% else %>
          <% @contact_requests_received.each do |contact_request| %>

            <div class="notification" id="cr-<%= contact_request.id %>">
              <% if contact_request.sender.avatar.attached? %>
                <% if contact_request.sender.avatar.content_type == mp4_content_type %>
                  <%= cl_video_tag contact_request.sender.avatar.key, transformation: [ crop: "fill" ], class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
                <% else %>
                  <%= cl_image_tag contact_request.sender.avatar.key, crop: :fill, class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
                <% end %>
              <% else %>
                <%= image_tag 'avatar-profil.png', class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
              <% end %>
              <div class="notification-content text-left">
                <p>
                  <small class="text-dark"><%= contact_request.created_at.to_date.strftime("%d/%m/%Y") %>, <%= link_to contact_request.sender.pseudo, profil_path(contact_request.sender.slug), class: "text-decoration-none" %></small>
                  <i class="fas fa-exclamation-circle ml-3 color-red <%= contact_request.readed ? 'hidden' : '' %>"></i>
                </p>
                <p><%= notifications_contact_request %></p>
              </div>
              <div class="notification-actions">
                <% if contact_request.accepted? %>
                  <i class="far fa-check-square" title="vous avez accepté cette demande"></i>
                <% end %>
                <% if policy(contact_request).mark_as_accepted? %>
                  <p class="btn-accepted">
                    <%= link_to mark_as_accepted_path(contact_request.id), remote: true, method: :patch, aria: { label: 'accepter cette demande de contact' } do %>
                      <span class="btn btn-primary" title="accepter cette demande de contact">Accepter</span>
                    <% end %>
                  </p>
                  <i class="far fa-check-square icon-accepted hidden" title="vous avez accepté cette demande"></i>
                <% end %>
                <% if policy(contact_request).hide_contact_request? %>
                  <p>
                    <%= link_to hide_contact_request_path(contact_request.id), remote: true, method: :patch, aria: { label: 'cacher cette demande de contact' } do %>
                      <i class="fas fa-eye-slash text-orange" title="Cacher cette demande de contact"></i>
                    <% end %>
                  </p>
                <% end %>
              </div>
            </div>

          <% end %>
          <%= will_paginate @contact_requests_received, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
        <% end %>
      </div>

    </div>

  </div>
</div>

app/views/contact_requests/hide_contact_request.js.erb
contactRequest = document.getElementById('cr-<%= @contact_request.id %>');

// hidden the contact request
contactRequest.classList.add('hidden');

app/views/contact_requests/mark_as_accepted.js.erb
contactRequest = document.getElementById('cr-<%= @contact_request.id %>');
btnAccepted = contactRequest.querySelector('.btn-accepted');
iconAccepted = contactRequest.querySelector('.icon-accepted');

// hidden the btn and display icon
btnAccepted.classList.add('hidden');
iconAccepted.classList.remove('hidden');