config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # Devise
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }
  #             path_names: { sign_in: '', sign_up: 'inscription', sign_out: 'deconnecter'}
  #             path: '',

  # if Rails.env == "development"
  #   devise_for :users, controllers: { registrations: 'registrations' }
  # elsif Rails.env == "production"
  #   devise_for :users, controllers: { registrations: 'users/registrations' }
  # end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # devise_scope :user do
  #   delete 'users/:id/delete-account', to: 'registrations#admin_destroy', as: :admin_destroy
  # end

  # Pages
  # get '/a-propos', to: 'pages#about_us', as: :about_us
  # get '/mentions-legales', to: 'pages#legal_notice', as: :legal_notice
  get '/accueil', to: 'pages#home', as: :home
  # root to: 'pages#home'
  get '/conditions-generales-de-vente', to: 'pages#cgv', as: :cgv
  get '/mes-profils-compatibles', to: 'pages#profil_match', as: :profil_match
  get '/admin-dashboard', to: 'pages#admin_dashboard', as: :admin_dashboard
  get '/admin-dashboard/profils', to: 'pages#admin_dashboard_profils', as: :admin_dashboard_profils
  get '/admin-dashboard/orders', to: 'pages#admin_dashboard_orders', as: :admin_dashboard_orders
  get '/admin-dashboard/messages', to: 'pages#admin_dashboard_messages', as: :admin_dashboard_messages
  get '/admin-dashboard/pages', to: 'pages#admin_dashboard_pages', as: :admin_dashboard_pages
  get '/profil/:slug', to: 'pages#profil', as: :profil
  get '/mes-favoris', to: 'pages#my_favorites', as: :my_favorites
  get '/profils-recherches', to: 'pages#search_profils', as: :search_profils
  get '/stories/:slug', to: 'pages#my_stories', as: :my_stories
  get '/stories', to: 'pages#all_stories', as: :all_stories
  delete 'users/:id/delete_photo_attachment', to: 'pages#delete_photo_attachment', as: :delete_photo_attachment_user
  get '/check-credit-activated', to: 'pages#check_credit_activated', as: :check_credit_activated
  # get '/mini-jeux', to: 'pages#applications', as: :applications
  patch '/user-banned/:id', to: 'pages#user_banned', as: :user_banned
  get '/profils-a-cote-de-ma-position-actuelle', to: 'pages#next_to_current_position', as: :next_to_current_position
  get '/update_position', to: 'pages#update_user_position',  as: :update_position

  # pages model
  get '/pages/:id/edit', to: 'pages#edit', as: :edit_page
  patch '/pages/:id', to: 'pages#update', as: :page
  put '/pages/:id', to: 'pages#update'

  # contact
  post '/contacts', to: 'messages#create', as: :messages
  get '/contact', to: 'messages#new', as: :new_message

  # favorites
  post '/favoris', to: 'favorites#create'
  delete '/favoris/:id', to: 'favorites#destroy', as: :favorite

  # publications
  get '/mur-des-publications', to: 'publications#filtered_index', as: :publications
  post '/mur-des-publications', to: 'publications#create'
  get '/publications/:id/edit', to: 'publications#edit', as: :edit_publication
  patch '/publications/:id', to: 'publications#update', as: :publication
  put '/publications/:id', to: 'publications#update'
  delete '/publications/:id', to: 'publications#destroy'

  # contact requests
  get '/mes-demandes-de-contact', to: 'contact_requests#filtered_index', as: :contact_requests
  post '/mes-demandes-de-contact', to: 'contact_requests#create'
  delete '/mes-demandes-de-contact/:id', to: 'contact_requests#destroy', as: :contact_request # destroy useless
  patch '/demande-de-contact-acceptee/:id', to: 'contact_requests#mark_as_accepted', as: :mark_as_accepted
  patch '/demande-de-contact-cachee/:id', to: 'contact_requests#hide_contact_request', as: :hide_contact_request

  # notifications
  get '/notifications', to: 'notifications#filtered_index', as: :notifications
  patch '/mode-invisible', to: 'notifications#ninja_mode', as: :ninja_mode
  patch '/notification-cachee/:id', to: 'notifications#hide_notification', as: :hide_notification

  # blockages
  get '/mes-comptes-bloques', to: 'blockages#filtered_index', as: :blockages
  post '/mes-comptes-bloques', to: 'blockages#create'
  delete '/mes-comptes-bloques/:id', to: 'blockages#destroy', as: :blockage

  # orders
  get '/mes-commandes', to: 'orders#filtered_index', as: :orders
  post '/mes-commandes', to: 'orders#create'
  delete '/mes-commandes/:id', to: 'orders#destroy', as: :order
  get '/ma-commande-en-cours', to: 'orders#current_order', as: :current_order
  get '/tarifs', to: 'orders#choose_prices', as: :choose_prices
  get '/mes-commandes/:id/payer', to: 'orders#pay_order', as: :pay_order
  get '/panier', to: 'orders#basket', as: :basket
  patch '/annuler-abonnement', to: 'orders#unsubcribed', as: :unsubcribed

  # payment page
  get '/mes-commandes/panier/:order_id/paiement', to: 'payments#new', as: :new_order_payment

  # chatrooms
  get '/chatrooms', to: 'chatrooms#index', as: :chatrooms
  get '/chatrooms/:id', to: 'chatrooms#show', as: :chatroom
  patch '/chatrooms/:id/depense-credit', to: 'chatrooms#use_credit', as: :use_credit

  # posts
  post '/chatrooms/:chatroom_id/posts', to: 'posts#create', as: :chatroom_posts

  # payment_intents
  get '/commandes/:order_id/paiements', to: 'payment_intents#filtered_index', as: :payment_intents
  patch '/commandes/:order_id/paiements/:id', to: 'payment_intents#refund', as: :refund
  patch '/paiements/:id/mise-a-jour-statut', to: 'payment_intents#check_refund_status', as: :check_refund_status

  # games
  # get '/jeux', to: 'games#index', as: :games
  # get '/jeux/:id', to: 'games#show', as: :game

  # error pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Stirpe webhook
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Sidekiq Web UI, only for admins.
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: "sender_id"
  belongs_to :receiver, class_name: 'User', foreign_key: "receiver_id"
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  after_action :mark_as_read, only: [:filtered_index]

  def filtered_index
    @user_notifications = authorize policy_scope(Notification).includes(:sender, :receiver).where(receiver: current_user, visible_receiver: true).order(id: :desc).paginate(page: params[:page], per_page: 50)
    @nbr_new_notifications = policy_scope(Notification).includes(:receiver).where(receiver: current_user, readed: false).size
  end

  def ninja_mode
    authorize :notification, :ninja_mode?

    time = params[:user][:ninja_time].to_i

    if (time <= current_user.ninja_time) && (time >= 1)
      current_user.update(ninja_activated: true)
      ReduceNinjaTimeJob.perform_later(current_user, time)
      DesactivateNinjaModeJob.set(wait: time.minute).perform_later(current_user)
      if current_user.ninja_reset == false
        current_user.update(ninja_reset: true)
        ResetNinjaTimeJob.set(wait_until: Date.tomorrow.beginning_of_day).perform_later(current_user)
      end
      return redirect_back fallback_location: notifications_path, notice: "Le mode invisible est activé pour #{time} minutes."
    else
      return redirect_back fallback_location: notifications_path, alert: "Veuillez sélectionner un temps < ou = à #{current_user.ninja_time} minutes."
    end
  end

  def hide_notification
    @notification = authorize policy_scope(Notification).find(params[:id])

    if @notification.sender == current_user
      HideElementSenderJob.perform_later(@notification)
    elsif @notification.receiver == current_user
      HideElementReceiverJob.perform_later(@notification)
    end

    respond_to do |format|
      format.js
      format.html { redirect_back fallback_location: notifications_path, notice: 'La notification a bien été cachée.' }
    end
  end

  private

  def mark_as_read
    notifications_not_readed = policy_scope(Notification).where(receiver: current_user, readed: false)

    notifications_not_readed.each do |notification|
      MarkAsReadJob.perform_later(notification)
    end
  end
end

app/helpers/notification_helper.rb
module NotificationHelper
  # contact_request
  def notifications_contact_request
    'vous a envoyé une demande de contact.'
  end

  def notifications_contact_request_sent
    'une demande de contact lui a été envoyée'
  end

  def notifications_contact_request_readed
    'a vu votre demande de contact.'
  end

  def notifications_contact_request_accepted
    'a accepté votre demande de contact.'
  end

  # favorite
  def notifications_favorite
    'vous a ajouté à ses favoris.'
  end

  # profil
  def notifications_profil
    'a vu votre profil.'
  end

  # blockage
  def notifications_blockage
    'vous avez bloqué cet utilisateur.'
  end

  # post
  def notifications_post
    'vous a envoyé un message privé.'
  end
end

app/views/notifications/filtered_index.html.erb
<div class="bg-gradient d-flex justify-content-around">
  <div class="publications-width bg-white p-2 p-md-5">

    <!-- title -->
    <h1 class="text-center">
      Mes notifications
      <span class="<%= @nbr_new_notifications.positive? ? 'counter' : '' %>">
        <%= @nbr_new_notifications.positive? ? @nbr_new_notifications : '' %>
      </span>
    </h1>

    <div class="col-12 mt-5">

      <!-- user notifications -->
      <% if @user_notifications.empty? %>

        <p><em>aucune</em></p>

      <% else %>

        <% @user_notifications.each do |notification| %>
          <div class="notification" id="notification-<%= notification.id %>">
            <% if notification.sender.avatar.attached? %>
              <% if notification.sender.avatar.content_type == mp4_content_type %>
                <%= cl_video_tag notification.sender.avatar.key, transformation: [ crop: "fill" ], class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
              <% else %>
                <%= cl_image_tag notification.sender.avatar.key, crop: :fill, class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
              <% end %>
            <% else %>
              <%= image_tag 'avatar-profil.png', class: "avatar-large", alt: 'avatar', loading: 'lazy' %>
            <% end %>
            <div class="notification-content">
              <p>
                <p class="text-dark"><%= notification.created_at.to_date.strftime("%d/%m/%Y") %>, <%= link_to notification.sender.pseudo, profil_path(notification.sender.slug), class: "text-decoration-none font-weight-bold" %></p>
                <i class="fas fa-exclamation-circle ml-3 color-red <%= notification.readed ? 'hidden' : '' %>"></i>
              </p>
              <p><%= notification.content %></p>
            </div>
            <div class="notification-actions">
              <% if policy(notification).hide_notification? %>
                <p>
                  <%= link_to hide_notification_path(notification.id), remote: true, method: :patch, aria: { label: 'cacher cette notification' } do %>
                    <i class="fas fa-eye-slash text-orange" title="Cacher cette notification"></i>
                  <% end %>
                </p>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= will_paginate @user_notifications, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      <% end %>

    </div>

  </div>
</div>

app/views/notifications/hide_notification.js.erb
notification = document.getElementById('notification-<%= @notification.id %>');

// hidden the contact request
notification.classList.add('hidden');