config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # Devise
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }
  #             path_names: { sign_in: '', sign_up: 'inscription', sign_out: 'deconnecter'}
  #             path: '',

  # if Rails.env == "development"
  #   devise_for :users, controllers: { registrations: 'registrations' }
  # elsif Rails.env == "production"
  #   devise_for :users, controllers: { registrations: 'users/registrations' }
  # end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # devise_scope :user do
  #   delete 'users/:id/delete-account', to: 'registrations#admin_destroy', as: :admin_destroy
  # end

  # Pages
  # get '/a-propos', to: 'pages#about_us', as: :about_us
  # get '/mentions-legales', to: 'pages#legal_notice', as: :legal_notice
  get '/accueil', to: 'pages#home', as: :home
  # root to: 'pages#home'
  get '/conditions-generales-de-vente', to: 'pages#cgv', as: :cgv
  get '/mes-profils-compatibles', to: 'pages#profil_match', as: :profil_match
  get '/admin-dashboard', to: 'pages#admin_dashboard', as: :admin_dashboard
  get '/admin-dashboard/profils', to: 'pages#admin_dashboard_profils', as: :admin_dashboard_profils
  get '/admin-dashboard/orders', to: 'pages#admin_dashboard_orders', as: :admin_dashboard_orders
  get '/admin-dashboard/messages', to: 'pages#admin_dashboard_messages', as: :admin_dashboard_messages
  get '/admin-dashboard/pages', to: 'pages#admin_dashboard_pages', as: :admin_dashboard_pages
  get '/profil/:slug', to: 'pages#profil', as: :profil
  get '/mes-favoris', to: 'pages#my_favorites', as: :my_favorites
  get '/profils-recherches', to: 'pages#search_profils', as: :search_profils
  get '/stories/:slug', to: 'pages#my_stories', as: :my_stories
  get '/stories', to: 'pages#all_stories', as: :all_stories
  delete 'users/:id/delete_photo_attachment', to: 'pages#delete_photo_attachment', as: :delete_photo_attachment_user
  get '/check-credit-activated', to: 'pages#check_credit_activated', as: :check_credit_activated
  # get '/mini-jeux', to: 'pages#applications', as: :applications
  patch '/user-banned/:id', to: 'pages#user_banned', as: :user_banned
  get '/profils-a-cote-de-ma-position-actuelle', to: 'pages#next_to_current_position', as: :next_to_current_position
  get '/update_position', to: 'pages#update_user_position',  as: :update_position

  # pages model
  get '/pages/:id/edit', to: 'pages#edit', as: :edit_page
  patch '/pages/:id', to: 'pages#update', as: :page
  put '/pages/:id', to: 'pages#update'

  # contact
  post '/contacts', to: 'messages#create', as: :messages
  get '/contact', to: 'messages#new', as: :new_message

  # favorites
  post '/favoris', to: 'favorites#create'
  delete '/favoris/:id', to: 'favorites#destroy', as: :favorite

  # publications
  get '/mur-des-publications', to: 'publications#filtered_index', as: :publications
  post '/mur-des-publications', to: 'publications#create'
  get '/publications/:id/edit', to: 'publications#edit', as: :edit_publication
  patch '/publications/:id', to: 'publications#update', as: :publication
  put '/publications/:id', to: 'publications#update'
  delete '/publications/:id', to: 'publications#destroy'

  # contact requests
  get '/mes-demandes-de-contact', to: 'contact_requests#filtered_index', as: :contact_requests
  post '/mes-demandes-de-contact', to: 'contact_requests#create'
  delete '/mes-demandes-de-contact/:id', to: 'contact_requests#destroy', as: :contact_request # destroy useless
  patch '/demande-de-contact-acceptee/:id', to: 'contact_requests#mark_as_accepted', as: :mark_as_accepted
  patch '/demande-de-contact-cachee/:id', to: 'contact_requests#hide_contact_request', as: :hide_contact_request

  # notifications
  get '/notifications', to: 'notifications#filtered_index', as: :notifications
  patch '/mode-invisible', to: 'notifications#ninja_mode', as: :ninja_mode
  patch '/notification-cachee/:id', to: 'notifications#hide_notification', as: :hide_notification

  # blockages
  get '/mes-comptes-bloques', to: 'blockages#filtered_index', as: :blockages
  post '/mes-comptes-bloques', to: 'blockages#create'
  delete '/mes-comptes-bloques/:id', to: 'blockages#destroy', as: :blockage

  # orders
  get '/mes-commandes', to: 'orders#filtered_index', as: :orders
  post '/mes-commandes', to: 'orders#create'
  delete '/mes-commandes/:id', to: 'orders#destroy', as: :order
  get '/ma-commande-en-cours', to: 'orders#current_order', as: :current_order
  get '/tarifs', to: 'orders#choose_prices', as: :choose_prices
  get '/mes-commandes/:id/payer', to: 'orders#pay_order', as: :pay_order
  get '/panier', to: 'orders#basket', as: :basket
  patch '/annuler-abonnement', to: 'orders#unsubcribed', as: :unsubcribed

  # payment page
  get '/mes-commandes/panier/:order_id/paiement', to: 'payments#new', as: :new_order_payment

  # chatrooms
  get '/chatrooms', to: 'chatrooms#index', as: :chatrooms
  get '/chatrooms/:id', to: 'chatrooms#show', as: :chatroom
  patch '/chatrooms/:id/depense-credit', to: 'chatrooms#use_credit', as: :use_credit

  # posts
  post '/chatrooms/:chatroom_id/posts', to: 'posts#create', as: :chatroom_posts

  # payment_intents
  get '/commandes/:order_id/paiements', to: 'payment_intents#filtered_index', as: :payment_intents
  patch '/commandes/:order_id/paiements/:id', to: 'payment_intents#refund', as: :refund
  patch '/paiements/:id/mise-a-jour-statut', to: 'payment_intents#check_refund_status', as: :check_refund_status

  # games
  # get '/jeux', to: 'games#index', as: :games
  # get '/jeux/:id', to: 'games#show', as: :game

  # error pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Stirpe webhook
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Sidekiq Web UI, only for admins.
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="status">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer role="contentinfo" aria-label="pied de page" id="footer" class="bg-dark text-white">
  <div class="container mt-1">
    <div class="row align-items-center justify-content-between">

      <!-- icons réseaux sociaux -->
      <div class="col-12 col-lg-3 text-center text-lg-left mb-4" aria-label="liens vers nos réseaux sociaux">
        <a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer" title="compte Facebook" aria-label="page facebook"><i class="fab fa-facebook"></i></a>
        <a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer" title="compte Instagram" aria-label="compte Instagram"><i class="fab fa-instagram"></i></a>
      </div>

      <!-- CGV & contact -->
      <address class="col-12 col-lg-9 d-flex flex-column flex-md-row justify-content-around text-center">
        <p><%= link_to 'Conditions Générales de Vente', cgv_path, class: "text-decoration-none text-14", target: "_blank", rel: "noopener noreferrer" %></p>
        <p><%= link_to 'Contactez-nous', new_message_path, class: "text-decoration-none text-14", target: "_blank", rel: "noopener noreferrer" %></p>
        <p class="text-14" aria-label="addresse mail de contact"><%= ENV['SUNRYSE_EMAIL'] %></p>
      </address>

    </div>
  </div>

  <!-- copyright -->
  <div class="bg-black text-center">
    <div class="container d-flex flex-column flex-lg-row justify-content-between align-items-center">
      <small class="font-weight-bold text-center my-2">Tous droits réservés | SUNRYSE 2021</small>
      <small class="mb-2 mb-lg-0 web-developer" aria-label="créateur du site"><em>Site créé par <a href="https://bertrand-bichat.github.io/" class="text-primary text-decoration-none" target="_blank" rel="noopener noreferrer author" title="créateur du site">Bertrand Bichat</a></em></small>
    </div>
  </div>

</footer>

app/views/shared/_info_window.html.erb
<div class="container">
  <div>
    <p class="pop-title"><%= user.pseudo %></p>
    <p class="pop-time">inscrit depuis le <%= user.created_at.to_date.strftime("%d-%m-%Y") %></p>
    <p class="pop-user"><%= user.age %> ans</p>
    <%= link_to profil_path(user.slug) do %>
      <i class="fas fa-eye" title="Voir son profil"></i>
    <% end %>
  </div>
</div>

app/views/shared/_order_card.html.erb
<div class="border p-3 my-3 col-12 col-md-4 text-center" id="order-<%= order.id %>">
  <!-- data -->
  <p>
    <% if order.order_type == order_type_subscription %>
      Abonnement mensuel
    <% elsif order.order_type == order_type_camera %>
      <%= order.camera_credits %> crédits d'échange par caméra
    <% else %>
      Tarif découverte
    <% end %>
  </p>
  <p>Durée : <%= order.order_type == order_type_camera ? "#{order.camera_credits*30} min" : order.duration %></p>
  <p>Prix TTC : <%= humanized_money(order.amount) %><%= order.order_type == order_type_subscription ? '€/mois' : '€' %></p>

  <% if order.state == order_state_payed %>
    <p>Payée <%= order.paid_date.to_date.strftime("le %d/%m/%Y") %></p>
    <% unless order.order_type == order_type_camera %>
      <p class="<%= order.active? ? 'text-green' : 'color-red' %> font-weight-bold"><%= order.active? ? 'Actif' : 'Inactif' %></p>
    <% end %>
    <% if policy(order).unsubcribed? %>
      <p>
        <%= link_to unsubcribed_path(order_id: order.id), method: :patch, data: { confirm: 'Êtes-vous sûr de vouloir résilier votre abonnement ?' }, class: "btn btn-primary" do %>
          Arrêter l'abonnement
        <% end %>
      </p>
    <% elsif (order.order_type == order_type_subscription) && (order.active == false) %>
      <p>Résilié <%= order.cancel_date.strftime("le %d/%m/%Y") %></p>
    <% end %>
  <% end %>

  <!-- buttons -->
  <% if policy(order).destroy? %>
    <p>
      <%= link_to order_path(order.id), remote: true, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir annuler cette commande ?' }, class: "btn btn-primary" do %>
        Annuler
      <% end %>
    </p>
  <% end %>
  <% if policy(order).pay_order? %>
    <p>
      <%= link_to pay_order_path(order.id), class: "btn btn-primary" do %>
        Payer
      <% end %>
    </p>
  <% end %>
</div>

app/views/shared/_profiles_list.html.erb
<div class="row text-center mt-5">

  <% users.each do |user| %>
    <div class="col-12 col-md-6 col-lg-3 match-avatar my-5" title="<%= user.pseudo %>" id="user-<%= user.id %>">

      <%= link_to profil_path(user.slug), class: "text-decoration-none font-weight-bold" do %>

        <!-- avatar -->
        <% if user.avatar.attached? %>
          <div>
            <% if user.avatar.content_type == mp4_content_type %>
              <%= cl_video_tag user.avatar.key, transformation: [ height: 105, width: 105, crop: "fill", radius: 'max' ], class: "mt-2", alt: 'avatar', loading: 'lazy' %>
            <% else %>
              <%= cl_image_tag user.avatar.key, crop: :fill, class: "avatar-extralarge my-2", alt: 'avatar', loading: 'lazy' %>
            <% end %>
          </div>
        <% else %>
          <i class="fas fa-user my-2 profil-match"></i>
        <% end %>
        <br>
        <%= user.pseudo %>

        <!-- green dot -->
        <% if user.online? %>
          <div class="<%= user.avatar.attached? ? "dot-avatar" : "dot" %>"></div>
        <% end %>

      <% end %>

      <% if request.fullpath == "/mes-favoris" %>
        <% favorite = policy_scope(Favorite).where(user_id: current_user.id, profile_id: user.id).first %>
        <%= link_to favorite_path(favorite.id), remote: true, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir retirer ce profil de vos favoris ?' }, aria: { label: 'Supprimer de mes favoris' }, class: "ml-2" do %>
          <i class="far fa-trash-alt text-orange" title="Retirer ce profil de mes favoris"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_publication_card.html.erb
<div class="col-12 border px-3 pt-3 pb-0 mb-3" id="<%= publication.id %>">
  <div class="d-flex justify-content-between">

    <!-- content -->
    <p class="<%= publication.user == current_user ? 'order-1' : 'order-2' %> text-wrap">
      <%= publication.content %>
    </p>

    <div class="<%= publication.user == current_user ? 'order-2 ml-5' : 'order-1 mr-5' %>">

      <!-- author -->
      <p>
        <% if publication.user.admin? %>
          <span class="text-orange font-weight-bold"><%= publication.user.pseudo %></span>
        <% else %>
          <%= link_to profil_path(publication.user.slug), class: "font-weight-bold" do %>
            <%= publication.user.pseudo %>
          <% end %>
        <% end %>
      </p>

      <!-- date -->
      <p class="text-dark"><%= publication.created_at.to_date.strftime("%d/%m/%Y") %></p>

      <!-- buttons to edit and delete -->
      <div class="d-flex justify-content-end">
        <!-- edit -->
        <% if policy(publication).edit? %>
          <p class="mr-3">
            <%= link_to edit_publication_path(publication.id), aria: { label: 'Modifier ma publication' } do %>
              <i class="fas fa-edit text-orange" title="Modifier cette publication"></i>
            <% end %>
          </p>
        <% end %>
        <!-- delete -->
        <% if policy(publication).destroy? %>
          <p>
            <%= link_to publication_path(publication.id), remote: true, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cette publication ?' }, aria: { label: 'Supprimer ma publication' } do %>
              <i class="fas fa-trash-alt text-orange" title="Supprimer cette publication"></i>
            <% end %>
          </p>
        <% end %>
      </div>

    </div>

  </div>
</div>

app/views/shared/_stories_card.html.erb
<div class="bg-gradient">
  <div class="container bg-white pb-5 text-center">

    <% if user.class == User %>
      <h1 class="text-center py-5">Stories de <%= user.pseudo %></h1>
    <% else %>
      <h1 class="text-center py-5">Toutes les Stories</h1>
    <% end %>

    <% if stories.present? %>

      <div class="row w-100">
        <% stories.each do |story| %>
          <% person = User.find(story.record_id) %>
          <div class="d-flex flex-column align-items-center col-12 col-md-6 col-lg-4 mb-3" id="photo-<%= story.key %>">
            <% if story.content_type == mp4_content_type %>
              <%= cl_video_tag story.key, controls: true, transformation: [ height: 300, width: 300, crop: "fill"], class: "m-2", alt: "#{story.filename}", loading: 'lazy' %>
            <% else %>
              <%= cl_image_tag story.key, height: 300, width: 300, crop: :fill, class: "m-2", alt: "#{story.filename}", loading: 'lazy' %>
            <% end %>

            <div class="d-flex">
              <%= link_to profil_path(person.slug), class: "text-decoration-none font-weight-bold" do %>
                <%= person.pseudo %>
              <% end %>

              <!-- green dot -->
              <% if person.online? %>
                <div class="dot-stories ml-2 mt-1" title="en ligne"></div>
              <% end %>
            </div>

            <% if (user.class == User) && (user == current_user || current_user.admin?) %>
              <%= link_to delete_photo_attachment_user_path(story.signed_id), remote: true, method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer la story #{story.filename} ?" }, aria: { label: 'Supprimer cette story' } do %>
                <i class="fas fa-trash-alt text-orange" title="Supprimer la story <%= story.filename %>"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
        <%= will_paginate stories, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>

    <% else %>

      <h2 class="mt-5"><em>Aucune story n'a été publiée pour l'instant.</em></h2>

    <% end %>

  </div>
</div>